/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclerentalsys;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;


/**
 *
 * @author Sabari Roy
 */
public class CustomerRegistration extends javax.swing.JFrame {
   private static String usr = null;
    String file_name ="";
    String dest_file_path = "C:\\Users\\USER\\Documents\\NetBeansProjects\\VehicleRentalSys\\licence\\";
    Boolean error_flag = true;
     JFileChooser jFileChooser1 = new JFileChooser("C:\\Users\\USER\\Documents\\NetBeansProjects\\VehicleRentalSys\\licence\\copiesfromscanner\\");
    File f;
    File NewName;

    /**
     * Creates new form CustomerRegistration
     * 
     */
     
    public CustomerRegistration(String usr) {
        this.usr = usr;
       
        initComponents();
        autoUpdateCustID();
        resetFunction();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        srchField = new javax.swing.JTextField();
        notify = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new customer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel4.setText("Address*");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua & Deps", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Rep", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Congo {Democratic Rep}", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland {Republic}", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea North", "Korea South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar, {Burma}", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "St Kitts & Nevis", "St Lucia", "Saint Vincent & the Grenadines", "Samoa", "San Marino", "Sao Tome & Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad & Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" }));
        jComboBox1.setBorder(new LineBorder(Color.GRAY,1));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField5.setBorder(new LineBorder(Color.GRAY,1));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cust Last Name*");

        jTextField3.setBorder(new LineBorder(Color.GRAY,1));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel7.setText("PIN Code*");

        jLabel1.setText("Customer ID");

        jLabel2.setText("Cust First Name*");

        jTextField4.setBorder(new LineBorder(Color.GRAY,1));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField2.setBorder(new LineBorder(Color.GRAY,1));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("City*");

        jTextPane1.setBorder(new LineBorder(Color.GRAY,1));
        jTextPane1.setPreferredSize(new java.awt.Dimension(13, 24));
        jTextPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jLabel6.setText("Country*");

        jLabel9.setText("Phone Number*");

        jTextField6.setBorder(new LineBorder(Color.GRAY,1));
        jTextField6.setMinimumSize(new java.awt.Dimension(12, 29));
        jTextField6.setPreferredSize(new java.awt.Dimension(12, 30));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jLabel8.setText("Driving Licence*");

        jButton1.setText("Select file");
        jButton1.setBorder(new LineBorder(Color.GRAY,1));
        jButton1.setPreferredSize(new java.awt.Dimension(81, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4)
                            .addComponent(jComboBox1, 0, 185, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modify");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jLabel10.setText("Search");

        srchField.setBorder(new LineBorder(Color.GRAY,1));
        srchField.setMinimumSize(new java.awt.Dimension(12, 29));
        srchField.setPreferredSize(new java.awt.Dimension(12, 30));
        srchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                srchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                srchFieldFocusLost(evt);
            }
        });
        srchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchFieldActionPerformed(evt);
            }
        });
        srchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                srchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                srchFieldKeyTyped(evt);
            }
        });

        notify.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        notify.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                    .addComponent(srchField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(notify, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(srchField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Information"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust ID", "First Name", "Last Name", "Address", "City", "Country", "PIN Code", "Phone Number", "DL IMG ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//cfpl.setVisible(true);
   
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", ".jpeg","jpeg",".png",".JPG","JPG",".jpg","jpg");
        jFileChooser1.setAcceptAllFileFilterUsed(false);
            jFileChooser1.addChoosableFileFilter(filter);
            
               //  jFileChooser1.setFileFilter(filter);
               try{
                     jFileChooser1.showOpenDialog(null);
                          f = jFileChooser1.getSelectedFile();
                         file_name = f.getName();
                     
             
                         jButton1.setLabel(file_name);
                         
                  
               }
               catch(NullPointerException e)
                       {
                           //System.out.println("No files chosen");
                            jButton1.setLabel("No file selected");
                                
                       }
               
               
                
            //System.out.println(file_name);
                
            

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        RentalMainForm rf = new RentalMainForm(usr);
        rf.show();
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(error_flag == true)
        {
             JOptionPane.showMessageDialog(this, "Please fill all mandatory fields","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(file_name.equals("") || file_name == "")
        {
            notify.setText("No file choosen");
        }
        else 
        {
            notify.setText("");
            
              copyFiles(f);   
                String cust_id = jTextField1.getText();
                String cust_firstName = jTextField2.getText();
                String cust_lastName = jTextField3.getText();
                String cust_address = jTextPane1.getText();
                String cust_city = jTextField4.getText();
                String cust_country = jComboBox1.getSelectedItem().toString();
                String cust_pincode =  jTextField5.getText();
                String cust_phone = jTextField6.getText();
                String cust_fl_name = NewName.getName();
                
            try {
                String ins_query = "INSERT INTO `customer`(`cust_id`, `cust_fname`, `cust_lname`, `cust_adrs`, `cust_city`, `cust_country`, `cust_pin`, `cust_ph_num`, `cust_dl_fl_name`) VALUES ('"+cust_id+"','"+cust_firstName+"','"+cust_lastName+"','"+cust_address+"','"+cust_city+"','"+cust_country+"',"+cust_pincode+","+cust_phone+",'"+cust_fl_name+"')";
                   System.out.println("Working till here");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
                PreparedStatement stmnt = con.prepareStatement(ins_query);
              
             
              int dlgBx = JOptionPane.showConfirmDialog(null,"Please verify the data \nCustomer ID: \t"+cust_id+"\nCustomer Name: \t"+cust_firstName+" "+cust_lastName+"\nCustomer Address: \t"+cust_address+"\nCustomer city : \t"+cust_city+"\nCustomer Country: \t"+cust_country+"\nCustomer PIN: \t"+cust_pincode+"\nCustomer Phone: \t"+cust_phone+"\nCustomer DL: "+f.getName(),"Confirm?",JOptionPane.YES_NO_OPTION);
              if(dlgBx == JOptionPane.OK_OPTION)
              {
                  System.out.println(ins_query);
                 stmnt.executeUpdate(ins_query);
                 JOptionPane.showMessageDialog(this, "Customer "+cust_firstName+" "+cust_lastName+" added successfully");
                  resetFunction();
              }
             
                
                
                
              
            } catch (SQLException ex) {
                Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        resetFunction();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
       if(jTextField2.getText().equals("") || jTextField2.getText() == "")
       {
          notify.setText("First Name cannot be empty");
           
           jTextField2.setBorder(new LineBorder(Color.red,1));
           error_flag = true;
           
           //jTextField2.setBorder(new LineBorder(Color.gray,1));
           error_flag = true;
          
       }
       else
       {
           jTextField2.setText(jTextField2.getText().toUpperCase().trim());
           jTextField2.setBorder(new LineBorder(Color.GRAY,1));
           notify.setText("");
           error_flag = false;
       }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
       if(jTextField3.getText().equals("") || jTextField3.getText() == "")
       {
           notify.setText("Last Name cannot be empty");
           
           jTextField3.setBorder(new LineBorder(Color.red,1));
           error_flag = true;
           
       }
       else
       {
           jTextField3.setText(jTextField3.getText().toUpperCase().trim());
           jTextField3.setBorder(new LineBorder(Color.GRAY,1));
           notify.setText("");
           error_flag = false;
       }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane1FocusLost
        if(jTextPane1.getText().equals("") || jTextPane1.getText() == "")
       {
           notify.setText("Address cannot be empty");
           
           jTextPane1.setBorder(new LineBorder(Color.red,1));
           error_flag = true;
           
       }
       else
       {
           jTextPane1.setText(jTextPane1.getText().toUpperCase().trim());
           jTextPane1.setBorder(new LineBorder(Color.GRAY,1));
           notify.setText("");
           error_flag = false;
       }
    }//GEN-LAST:event_jTextPane1FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        if(jTextField4.getText().equals("") || jTextField4.getText() == "")
       {
           notify.setText("City cannot be empty");
           
           jTextField4.setBorder(new LineBorder(Color.red,1));
           error_flag = true;
           
       }
       else
       {
           jTextField4.setText(jTextField4.getText().toUpperCase().trim());
           jTextField4.setBorder(new LineBorder(Color.GRAY,1));
           notify.setText("");
           error_flag = false;
       }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
         if(jTextField5.getText().equals("") || jTextField5.getText() == "")
       {
           notify.setText("PIN Code cannot be empty");
           
           jTextField5.setBorder(new LineBorder(Color.red,1));
           error_flag = true;
           
       }
       else
       {
           jTextField5.setText(jTextField5.getText().toUpperCase().trim());
           jTextField5.setBorder(new LineBorder(Color.GRAY,1));
           notify.setText("");
           error_flag = false;
       }
        
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        if(jTextField6.getText().equals("") || jTextField6.getText() == "")
        {
            notify.setText("Phone Number cannot be empty");

            jTextField6.setBorder(new LineBorder(Color.red,1));
            error_flag = true;

        }
        else
        {
            jTextField6.setText(jTextField6.getText().toUpperCase().trim());
            jTextField6.setBorder(new LineBorder(Color.GRAY,1));
            notify.setText("");
            error_flag = false;
        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
    
    {
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8)
        {
     
       jTextField5.setEditable(true);
        }
        else
        {
            jTextField5.setEditable(false);
            notify.setText("Only numbers are allowed");
        }
        if(jTextField5.getText().length()>=6)
        {
            jTextField5.setText(jTextField5.getText().substring(0,5));
            //notify.setText("Limit reached");
        }
        
        
            
    }
    
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
         if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8)
        {
     
       jTextField6.setEditable(true);
        }
        else
        {
            jTextField6.setEditable(false);
            notify.setText("Only numbers are allowed");
        }
        if(jTextField6.getText().length()>=10)
        {
            jTextField6.setText(jTextField6.getText().substring(0,9));
           // notify.setText("Limit reached");
        }
        
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 jButton4.setEnabled(true);
jButton5.setEnabled(true);
        if(jTextField2.getText().equals("") || jTextField2.getText() == "")
       {
           notify.setText("First Name cannot be empty");
           
           jTextField2.setBorder(new LineBorder(Color.red,1));
           error_flag = true;
           
       }  
else
  {
      notify.setText("");
           
           jTextField2.setBorder(new LineBorder(Color.gray,1));
           error_flag = true;
  }
//to remove the red borders from field validations 
        jTextField2.setBorder(new LineBorder(Color.GRAY,1));
    jTextField3.setBorder(new LineBorder(Color.GRAY,1));
    jTextField4.setBorder(new LineBorder(Color.GRAY,1));
    jTextPane1.setBorder(new LineBorder(Color.GRAY,1));
    jTextField5.setBorder(new LineBorder(Color.GRAY,1));
    jTextField6.setBorder(new LineBorder(Color.GRAY,1));
        notify.setText("");
        
        DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
        int rowNum = jTable1.getSelectedRow();
            
        jTextField1.setText(dft.getValueAt(rowNum,0).toString());
             jTextField2.setText(dft.getValueAt(rowNum,1).toString());
                 jTextField3.setText(dft.getValueAt(rowNum,2).toString());
                     jTextPane1.setText(dft.getValueAt(rowNum,3).toString());
                         jTextField4.setText(dft.getValueAt(rowNum,4).toString());
                               jComboBox1.setSelectedItem(dft.getValueAt(rowNum,5));
                                 jTextField5.setText(dft.getValueAt(rowNum,6).toString());
                                     jTextField6.setText(dft.getValueAt(rowNum,7).toString());
                                     jButton2.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
      
    }//GEN-LAST:event_jTextField3FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Boolean file_flag = false;
        String cust_fl_name ="";
                  DbConUpdate update = new DbConUpdate();
        if(modifyErrorCheck())
        {
             JOptionPane.showMessageDialog(this, "Please fill all mandatory fields","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
           try{
               if(jFileChooser1.getSelectedFile() == null)
               {
                //  System.out.println("No file to update");
                  
               }
                else
               {
                   
                   file_flag = true; 
                  
                   
               }
           }
           catch(NullPointerException e)
           {
               System.err.println("Caught");
           }
              
                   
                String cust_id = jTextField1.getText();
                String cust_firstName = jTextField2.getText();
                String cust_lastName = jTextField3.getText();
                String cust_address = jTextPane1.getText();
                String cust_city = jTextField4.getText();
                String cust_country = jComboBox1.getSelectedItem().toString();
                String cust_pincode =  jTextField5.getText();
                String cust_phone = jTextField6.getText();
               
                if(file_flag)
                {
             int dlgBx = JOptionPane.showConfirmDialog(null,"Please verify the data \nCustomer ID: \t"+cust_id+"\nCustomer Name: \t"+cust_firstName+" "+cust_lastName+"\nCustomer Address: \t"+cust_address+"\nCustomer city : \t"+cust_city+"\nCustomer Country: \t"+cust_country+"\nCustomer PIN: \t"+cust_pincode+"\nCustomer Phone: \t"+cust_phone+"\nCustomer DL: "+f.getName(),"Confirm",JOptionPane.YES_NO_OPTION);
             if(dlgBx == JOptionPane.OK_OPTION)
             {
                 copyFiles(f);
                 cust_fl_name = NewName.getName();
                 String query = "UPDATE `customer` SET `cust_fname`='"+cust_firstName+"',`cust_lname`='"+cust_lastName+"',`cust_adrs`='"+cust_address+"',`cust_city`='"+cust_city+"',`cust_country`='"+cust_country+"',`cust_pin`='"+cust_pincode+"',`cust_ph_num`='"+cust_phone+"',`cust_dl_fl_name`='"+cust_fl_name+"',`cust_create_tmstmp`= CURRENT_TIMESTAMP WHERE `cust_id` = '"+cust_id+"'";
                 //System.err.println(query);
               
                 try {
                     update.updateDb(query);
                 } catch (SQLException ex) {
                     Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 JOptionPane.showMessageDialog(this, "Customer "+cust_id+" updated successfully");
             }
        }
                else
                {
                     int dlgBx = JOptionPane.showConfirmDialog(null,"Please verify the data \nCustomer ID: \t"+cust_id+"\nCustomer Name: \t"+cust_firstName+" "+cust_lastName+"\nCustomer Address: \t"+cust_address+"\nCustomer city : \t"+cust_city+"\nCustomer Country: \t"+cust_country+"\nCustomer PIN: \t"+cust_pincode+"\nCustomer Phone: \t"+cust_phone,"Confirm",JOptionPane.YES_NO_OPTION);
                     if(dlgBx == JOptionPane.OK_OPTION)
                     {
                     String query = "UPDATE `customer` SET `cust_fname`='"+cust_firstName+"',`cust_lname`='"+cust_lastName+"',`cust_adrs`='"+cust_address+"',`cust_city`='"+cust_city+"',`cust_country`='"+cust_country+"',`cust_pin`='"+cust_pincode+"',`cust_ph_num`='"+cust_phone+"',`cust_create_tmstmp`= CURRENT_TIMESTAMP WHERE `cust_id` = '"+cust_id+"'";
                         try {
                             update.updateDb(query);
                         } catch (SQLException ex) {
                             Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
                         }
                         JOptionPane.showMessageDialog(this, "Customer "+cust_id+" updated successfully");
                         
                     }     
                    // System.err.println(query);
                        
                }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String cust_id = jTextField1.getText().trim();
        String fName = jTextField2.getText();
        String lName = jTextField3.getText();
        DbConDelete del = new DbConDelete();
        String query = "DELETE FROM `customer` WHERE `cust_id` = ? ";
            int rs = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete ?", "Warning", JOptionPane.OK_CANCEL_OPTION);
                if(rs == JOptionPane.OK_OPTION)
                {
            try {
                del.deleteDb(query, cust_id);
               
            } catch (SQLException ex) {
                Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
                     JOptionPane.showMessageDialog(this, "Customer "+fName+" "+lName+" deleted successfully");
                      resetFunction();
                     
                }
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void srchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srchFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_srchFieldFocusLost

    private void srchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchFieldActionPerformed

    private void srchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyPressed
        searchByRegNum();
    }//GEN-LAST:event_srchFieldKeyPressed

    private void srchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srchFieldFocusGained
        jTextField2.setBorder(new LineBorder(Color.GRAY,1));
        notify.setText("");
    }//GEN-LAST:event_srchFieldFocusGained

    private void srchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyReleased
       searchByRegNum();
    }//GEN-LAST:event_srchFieldKeyReleased

    private void srchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyTyped
       searchByRegNum();
    }//GEN-LAST:event_srchFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistration(usr).setVisible(true);
            }
        });
    }
    private void autoUpdateCustID()
    {
        
        Connection con;
        try {
            String query = "SELECT MAX(`cust_id`) FROM customer;";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
                PreparedStatement stmt = con.prepareStatement(query);
                   ResultSet rs = stmt.executeQuery();
                        rs.next();
                            if(rs.getString("MAX(`cust_id`)") == null)
                                {
                                jTextField1.setText("C0001");
                                }
                             else
            {
                long id =  Long.parseLong(rs.getString("MAX(`cust_id`)").substring(2,rs.getString("MAX(`cust_id`)").length()));
                id++;       
                jTextField1.setText("C0" + String.format("%03d", id)); 
               
                
            }
                            
                        
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void resetFunction()
{
    autoUpdateCustID();
    tableUpdate();
    jTextField2.setText("");
    jTextField2.grabFocus();
    jTextField3.setText("");
    jTextField4.setText("");
    jTextPane1.setText("");
    jComboBox1.setSelectedIndex(75);
    jTextField5.setText("");
    jTextField6.setText("");
    jButton1.setText("No file selected");
    jTextField2.setBorder(new LineBorder(Color.GRAY,1));
    jTextField3.setBorder(new LineBorder(Color.GRAY,1));
    jTextField4.setBorder(new LineBorder(Color.GRAY,1));
    jTextPane1.setBorder(new LineBorder(Color.GRAY,1));
    jTextField5.setBorder(new LineBorder(Color.GRAY,1));
    jTextField6.setBorder(new LineBorder(Color.GRAY,1));
    notify.setText("");
    jButton2.setEnabled(true);
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    
}


public void copyFiles(File src)
        
{
    String[] ext = src.getName().split("\\.");
    int ext_index = ext.length - 1;
    String extension = ext[ext_index];
    String newName = jTextField1.getText().toUpperCase().trim();
            File dest = new File(dest_file_path+src.getName());
             NewName = new File(dest_file_path+newName+"."+extension);
            
 if(NewName.exists())
 {
     NewName.delete();
 }
    
    try{
      
        
        FileUtils.copyFile(src, dest);
//        System.out.println(extension);
//        System.out.println(newName);
//        System.out.println(NewName.getAbsoluteFile());
        dest.renameTo(NewName);
        
        
        
    }
    catch(IOException e)
    {
    }
    
}
 private void tableUpdate()
    {
        ResultSetMetaData rsmd = null;
        Integer count;
     String query = "SELECT `cust_id`, `cust_fname`, `cust_lname`, `cust_adrs`, `cust_city`, `cust_country`, `cust_pin`, `cust_ph_num`, `cust_dl_fl_name` FROM `customer`";
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
            PreparedStatement stmnt = con.prepareStatement(query);  
            ResultSet rs = stmnt.executeQuery();
             rsmd = rs.getMetaData();
            count = rsmd.getColumnCount();
                while(rs.next())
                  
                {                             
                              Vector v1 = new Vector();
                              for(int i = 1; i<= count;i++ ) 
                              {
                              v1.add(rs.getString(1));
                              v1.add(rs.getString(2));
                              v1.add(rs.getString(3));
                              v1.add(rs.getString(4));
                              v1.add(rs.getString(5));
                              v1.add(rs.getString(6));
                              v1.add(rs.getString(7));
                              v1.add(rs.getString(8));
                              v1.add(rs.getString(9));
                              }
                              model.addRow(v1);
                }
                
                
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
         jTable1.setAutoCreateRowSorter(true);
                              
    }
 private boolean modifyErrorCheck()
 {
     Boolean errorFlag2 = false;
     if(jTextField1.getText().equals(""))
     {
         errorFlag2 = true;
     }
     else if(jTextField2.getText().equals(""))
     {
         errorFlag2 = true;
     }
      else if(jTextField3.getText().equals(""))
     {
         errorFlag2 = true;
     }
      else if(jTextPane1.getText().equals(""))
     {
         errorFlag2 = true;
     }
      else if(jTextField4.getText().equals(""))
     {
         errorFlag2 = true;
     }
      else if(jTextField5.getText().equals(""))
     {
         errorFlag2 = true;
     }
      else if(jTextField6.getText().equals(""))
     {
         errorFlag2 = true;
     }
     else
      {
          errorFlag2 = false;
      }
     return errorFlag2;
 }
 
 private void searchByRegNum()
    {
        
        ResultSetMetaData rsmd = null;
        Integer count;
        String searchKey = srchField.getText().trim().toUpperCase();
     String query = "SELECT `cust_id`, `cust_fname`, `cust_lname`, `cust_adrs`, `cust_city`, `cust_country`, `cust_pin`, `cust_ph_num`, `cust_dl_fl_name` FROM `customer` WHERE `cust_id`LIKE '"+searchKey+"%'OR `cust_fname`LIKE '"+searchKey+"%' OR `cust_lname` LIKE '"+searchKey+"%'";
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
          
           
           
           
        try {
            DbConSelect db = new DbConSelect();
            
  
            ResultSet rs = db.selectDb(query);
             rsmd = rs.getMetaData();
             
            count = rsmd.getColumnCount();
           
         
            
                while(rs.next())
                  
                {                             
                              Vector v1 = new Vector();
                              for(int i = 1; i<= count;i++ ) 
                              {
                              v1.add(rs.getString(1));
                              v1.add(rs.getString(2));
                              v1.add(rs.getString(3));
                              v1.add(rs.getString(4));
                              v1.add(rs.getString(5));
                              v1.add(rs.getString(6));
                              v1.add(rs.getString(7));
                              v1.add(rs.getString(8));
                              v1.add(rs.getString(9));
                              }
                              model.addRow(v1);
                }
                            
                            //System.out.print(rowCount);
                            if(model.getRowCount() == 0)
                            {
                                JOptionPane.showMessageDialog(null,"Customer not found.","Error",JOptionPane.WARNING_MESSAGE);
                                srchField.setText(srchField.getText().substring(0, srchField.getText().length()-1));
                            resetFunction();
                            srchField.grabFocus();
                            
                            }
     
                
            
                
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
         jTable1.setAutoCreateRowSorter(true);
                              
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel notify;
    private javax.swing.JTextField srchField;
    // End of variables declaration//GEN-END:variables
}
