/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclerentalsys;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sabari Roy
 */
public class Vehicle_registration extends javax.swing.JFrame {
 public String currentID = null;
 public static String currentUser = null;
 
    /**
     * Creates new form Vehicle_registration
     */
    public Vehicle_registration(String userName) {
       
        initComponents();
        resetFunction();
        autoIdUpdate();
        this.currentUser = userName;
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        notifLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        srchField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehicle Registration");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        jPanel1.setToolTipText("To add/edit/delete vehicles from the system");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Vehicle ID");

        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Registration No.*");

        jTextField2.setBorder(new LineBorder(Color.GRAY,1));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Vehicle Type");

        jComboBox1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scooter", "Motor Cycle w/Gear", "Car", " " }));
        jComboBox1.setBorder(new LineBorder(Color.GRAY,1));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Insurance Start Dt");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Insurance End Dt");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Remarks/Comments");

        jTextPane1.setBorder(new LineBorder(Color.GRAY,1));
        jTextPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Vehicle Model*");

        jTextField3.setBorder(new LineBorder(Color.GRAY,1));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("Available");

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jComboBox2.setMaximumRowCount(3);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jComboBox2.setBorder(new LineBorder(Color.GRAY,1));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.setToolTipText("Add a new vehicle to the system");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sabari Roy\\Documents\\NetBeansProjects\\VehicleRentalSystem\\icons\\reset.png")); // NOI18N
        jButton1.setToolTipText("Reset all the fields");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Modify");
        jButton3.setToolTipText("Update an existing vehicle");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notifLabel.setForeground(new java.awt.Color(255, 0, 0));

        srchField.setToolTipText("Search by registration number");
        srchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                srchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                srchFieldKeyTyped(evt);
            }
        });

        jLabel9.setText("Search by Reg#");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(srchField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(srchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(jTextField2)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLayeredPane1)))
            .addComponent(notifLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Details"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Reg No.", "Vehicle Type", "Vehicle Model", "Availabilty", "Insurance Start Dt", "Insurance End Dt", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      resetFunction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
RentalMainForm rmf = new RentalMainForm(currentUser);
rmf.show();
       
    }//GEN-LAST:event_formWindowClosed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
           jTextField2.setText(jTextField2.getText().toUpperCase());
           jTextField2.setBorder(new LineBorder(Color.GRAY,1));
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        jTextField3.setText(jTextField3.getText().toUpperCase());
        jTextField3.setBorder(new LineBorder(Color.GRAY,1));
    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           Boolean flag1 = false;
        Boolean flag2 = false;
            String checkEmpty = jTextField2.getText();
                 String checkEmpty2 = jTextField3.getText();
          if(checkEmpty == null || checkEmpty.isEmpty())
             {  
                  flag1 = true;
               }
        if(checkEmpty2 == null || checkEmpty2.isEmpty())
             {
                     flag2 = true;
                 }
         //ends flag setting
        if(flag1)
        {
            JOptionPane.showMessageDialog(this, "Registration Number cannot be Empty","Warning", JOptionPane.WARNING_MESSAGE);
            jTextField2.grabFocus();
                    jTextField2.setBorder(new LineBorder(Color.red,1));
        }
             else if(flag2)
                     {
            JOptionPane.showMessageDialog(this, "Vehicle model cannot be Empty","Warning", JOptionPane.WARNING_MESSAGE);
             jTextField3.grabFocus();
                      jTextField3.setBorder(new LineBorder(Color.red,1));
       
                     }
        else
             {
              SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
              String vehicle_id = jTextField1.getText().toUpperCase().trim();
               String vehicle_number =  jTextField2.getText().toUpperCase().trim();
                String vehicle_type = jComboBox1.getSelectedItem().toString();
                     String vehicle_model = jTextField3.getText().toUpperCase().trim();
                      String availabilty = jComboBox2.getSelectedItem().toString().substring(0,1);
                               String ins_st_dt = df.format(jDateChooser1.getDate());
                               String ins_end_dt = df.format(jDateChooser2.getDate());
                                String remarks = jTextPane1.getText();
                              // System.out.println(vehicle_id+"\n"+vehicle_number+"\n"+vehicle_type+"\n"+vehicle_model+"\n"+availabilty+"\n"+ins_st_dt+"\n"+ins_end_dt+"\n"+remarks);
                               String query = "insert into `vehicle_details` (`v_id`,`v_reg_no`,`v_type`,`v_model`,`v_avble`,`v_ins_st_dt`,`v_ins_end_dt`,`v_remark`) values(?,?,?,?,?,?,?,?)";
                               String v_num_check = jTextField2.getText().toUpperCase().trim();
                               String query2 = "SELECT `v_reg_no` FROM `vehicle_details` where `v_reg_no` = ? ";
                               
                               
                               
               try {
                   Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
                   PreparedStatement stmnt2 = con.prepareStatement(query2);
                   stmnt2.setString(1,v_num_check);
                   ResultSet rs = stmnt2.executeQuery();
                   if(rs.next())
                   {
                       JOptionPane.showMessageDialog(this,"Vehicle number "+vehicle_number+" already exists!","Error", JOptionPane.ERROR_MESSAGE);
                   }
                   else
                   {
                   PreparedStatement stmnt = con.prepareStatement(query);
                        stmnt.setString(1,vehicle_id);
                        stmnt.setString(2, vehicle_number);
                        stmnt.setString(3, vehicle_type);
                        stmnt.setString(4,vehicle_model);
                        stmnt.setString(5,availabilty);
                        stmnt.setString(6,ins_st_dt);
                        stmnt.setString(7,ins_end_dt);
                        stmnt.setString(8,remarks);
                        stmnt.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Vehicle "+jTextField2.getText()+" added successfully");
                        resetFunction();
                   }
                        
               } catch (SQLException ex) {
                   Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
               }
                               
                              
                               
                               
                        
                   
             }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void tableUpdate()
    {
        ResultSetMetaData rsmd = null;
        Integer count;
     String query = "SELECT `v_id`, `v_reg_no`, `v_type`, `v_model`, `v_avble`, `v_ins_st_dt`, `v_ins_end_dt`, `v_remark` FROM `vehicle_details`";
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
            PreparedStatement stmnt = con.prepareStatement(query);  
            ResultSet rs = stmnt.executeQuery();
             rsmd = rs.getMetaData();
            count = rsmd.getColumnCount();
                while(rs.next())
                  
                {                             
                              Vector v1 = new Vector();
                              for(int i = 1; i<= count;i++ ) 
                              {
                              v1.add(rs.getString(1));
                              v1.add(rs.getString(2));
                              v1.add(rs.getString(3));
                              v1.add(rs.getString(4));
                              v1.add(rs.getString(5));
                              v1.add(rs.getString(6));
                              v1.add(rs.getString(7));
                              v1.add(rs.getString(8));
                              }
                              model.addRow(v1);
                }
                
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
         jTable1.setAutoCreateRowSorter(true);
                              
    }
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DefaultTableModel dft = (DefaultTableModel)jTable1.getModel();
      
        
                int rowNum = jTable1.getSelectedRow();
        String YorN;
        
           
            jTextField1.setText(dft.getValueAt(rowNum,0).toString());
                jTextField2.setText(dft.getValueAt(rowNum, 1).toString());
                    jComboBox1.setSelectedItem(dft.getValueAt(rowNum,2).toString());
                        jTextField3.setText(dft.getValueAt(rowNum,3).toString());
                     if(dft.getValueAt(rowNum, 4).toString().equals("Y"))
                     {
                         YorN = "Yes";
                         
                     }
                     else
                     {
                      YorN = "No";   
                     }
                            jComboBox2.setSelectedItem(YorN);
                             String d1 = dft.getValueAt(rowNum,5).toString();
           try {
           Date insStDt = df.parse(d1);
            jDateChooser1.setDate(insStDt);
        } catch (ParseException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
             String d2 = dft.getValueAt(rowNum, 6).toString();
        try {
          Date  insEndDt = df.parse(d2);
             jDateChooser2.setDate(insEndDt);
        } catch (ParseException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }                   
                                   
                                        jTextPane1.setText(dft.getValueAt(rowNum,7).toString());
                                        jButton3.setEnabled(true);
                                        jButton4.setEnabled(true);
                                            if(jTextPane1.getText().trim().equalsIgnoreCase("Rented"))
                                            {
                                                jComboBox2.setEnabled(false);
                                                jTextPane1.setEnabled(false);
                                                jButton4.setEnabled(false);
                                                notifLabel.setText("Rented vehicle cannot be modified/deleted");
                                               
                                            }
                                                else
                                            {
                                                 jComboBox2.setEnabled(true);
                                                jTextPane1.setEnabled(true);
                                                notifLabel.setText("");
                                            }
                                            //jTable1.setAutoCreateRowSorter(true);
                                    
                                                     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        jButton2.setEnabled(false);
      
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost

    }//GEN-LAST:event_jTable1FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       modifyTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DbConDelete db = new DbConDelete();
        String query = "DELETE FROM `vehicle_details` WHERE `v_id` = ?";
        String id = jTextField1.getText().toUpperCase().trim();
            int dlgbxRslt = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete vehicle data for "+jTextField2.getText().toUpperCase(),"Warning",JOptionPane.YES_NO_OPTION);
            if(dlgbxRslt == JOptionPane.YES_OPTION)
            {
        
     try {
         db.deleteDb(query, id);
         JOptionPane.showMessageDialog(this,"Vehicle data deleted successfully","Warning", JOptionPane.WARNING_MESSAGE);
     } catch (SQLException ex) {
         Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
     }
            }
                
            resetFunction();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane1FocusLost
        if(jTextPane1.getText().equalsIgnoreCase("Rented"))
        {
            jButton3.setEnabled(false);
            notifLabel.setText("Cannot use the keyword rented for modification");
        }
    }//GEN-LAST:event_jTextPane1FocusLost

    private void srchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyPressed
        searchByRegNum();
    }//GEN-LAST:event_srchFieldKeyPressed

    private void srchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyTyped
        // TODO add your handling code here:
        searchByRegNum();
    }//GEN-LAST:event_srchFieldKeyTyped

    private void srchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyReleased
        searchByRegNum();
    }//GEN-LAST:event_srchFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_registration(currentUser).setVisible(true);
            }
        });
    }
    private void resetFunction()
    {
         ZoneId defaultZoneId = ZoneId.systemDefault();
        LocalDate d1 = LocalDate.now();
        LocalDate d2 = d1.plusYears(1);
        Date dt = Date.from(d1.atStartOfDay(defaultZoneId).toInstant());
        Date dt2 = Date.from(d2.atStartOfDay(defaultZoneId).toInstant());
       
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jDateChooser1.setDate(dt);
        jDateChooser2.setDate(dt2);
        jTextPane1.setText("");
        autoIdUpdate();
        tableUpdate();
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
            if(srchField.getText().equals(""))
            {
                srchField.setText("");
            }
            else
            {
        srchField.setText(srchField.getText().substring(0,srchField.getText().length()-1));
            }
    }
private void autoIdUpdate()
        
{
    Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
                PreparedStatement stmt = con.prepareStatement("SELECT MAX(`v_id`) FROM `vehicle_details`");
                   ResultSet rs = stmt.executeQuery();
                        rs.next();
                            if(rs.getString("MAX(`v_id`)") == null)
                                {
                                jTextField1.setText("V0001");
                                }
                             else
            {
                long id =  Long.parseLong(rs.getString("MAX(`v_id`)").substring(2,rs.getString("MAX(`v_id`)").length()));
                id++;       
                jTextField1.setText("V0" + String.format("%03d", id)); 
               
                
            }
                        
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
}

private void modifyTable(){
     Boolean flag1 = false;
        Boolean flag2 = false;
            String checkEmpty = jTextField2.getText();
                 String checkEmpty2 = jTextField3.getText();
          if(checkEmpty == null || checkEmpty.isEmpty())
             {  
                  flag1 = true;
               }
        if(checkEmpty2 == null || checkEmpty2.isEmpty())
             {
                     flag2 = true;
                 }
         //ends flag setting
        if(flag1)
        {
            JOptionPane.showMessageDialog(this, "Registration Number cannot be Empty","Warning", JOptionPane.WARNING_MESSAGE);
            jTextField2.grabFocus();
                    jTextField2.setBorder(new LineBorder(Color.red,1));
        }
             else if(flag2)
                     {
            JOptionPane.showMessageDialog(this, "Vehicle model cannot be Empty","Warning", JOptionPane.WARNING_MESSAGE);
             jTextField3.grabFocus();
                      jTextField3.setBorder(new LineBorder(Color.red,1));
       
                     }
        else
             {
              SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
              String vehicle_id = jTextField1.getText().toUpperCase().trim();
               String vehicle_number =  jTextField2.getText().toUpperCase().trim();
                String vehicle_type = jComboBox1.getSelectedItem().toString();
                     String vehicle_model = jTextField3.getText().toUpperCase().trim();
                      String availabilty = jComboBox2.getSelectedItem().toString().substring(0,1);
                               String ins_st_dt = df.format(jDateChooser1.getDate());
                               String ins_end_dt = df.format(jDateChooser2.getDate());
                                String remarks = jTextPane1.getText();
                              // System.out.println(vehicle_id+"\n"+vehicle_number+"\n"+vehicle_type+"\n"+vehicle_model+"\n"+availabilty+"\n"+ins_st_dt+"\n"+ins_end_dt+"\n"+remarks);
                               String query = "UPDATE `vehicle_details` SET `v_reg_no`= ? ,`v_type`=? ,`v_model`=?,`v_avble`=?,`v_ins_st_dt`=?,`v_ins_end_dt`=?,`v_remark`=? WHERE `v_id` = ? ";
                               String v_num_check = jTextField2.getText().toUpperCase().trim();
                               String query2 = "SELECT `v_reg_no` FROM `vehicle_details` where `v_reg_no` = ? ";
                               
                               
                               
               try {
                   Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vehicle_db","root","");
                   PreparedStatement stmnt2 = con.prepareStatement(query2);
                   stmnt2.setString(1,v_num_check);
                   ResultSet rs = stmnt2.executeQuery();
                   
                   PreparedStatement stmnt = con.prepareStatement(query);
                        //stmnt.setString(1,vehicle_id);
                        stmnt.setString(1, vehicle_number);
                        stmnt.setString(2, vehicle_type);
                        stmnt.setString(3,vehicle_model);
                        stmnt.setString(4,availabilty);
                        stmnt.setString(5,ins_st_dt);
                        stmnt.setString(6,ins_end_dt);
                        stmnt.setString(7,remarks);
                        stmnt.setString(8,vehicle_id);
                        
                        stmnt.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Vehicle ID "+jTextField1.getText()+" Vehicle data modified successfully");
                        resetFunction();
                   
                        
               } catch (SQLException ex) {
                   Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
               }
                               
                              
                               
                               
                        
                   
             }
}
  private void searchByRegNum()
    {
        ResultSetMetaData rsmd = null;
        Integer count;
        String searchKey = srchField.getText().trim().toUpperCase();
     String query = "SELECT `v_id`, `v_reg_no`, `v_type`, `v_model`, `v_avble`, `v_ins_st_dt`, `v_ins_end_dt`, `v_remark` FROM `vehicle_details` where `v_reg_no` LIKE '"+searchKey+"%'";
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           Connection con;
        try {
            DbConSelect db = new DbConSelect();
            
  
            ResultSet rs = db.selectDb(query);
             rsmd = rs.getMetaData();
             
            count = rsmd.getColumnCount();
           
         
            
                while(rs.next())
                  
                {                             
                              Vector v1 = new Vector();
                              for(int i = 1; i<= count;i++ ) 
                              {
                              v1.add(rs.getString(1));
                              v1.add(rs.getString(2));
                              v1.add(rs.getString(3));
                              v1.add(rs.getString(4));
                              v1.add(rs.getString(5));
                              v1.add(rs.getString(6));
                              v1.add(rs.getString(7));
                              v1.add(rs.getString(8));
                              }
                              model.addRow(v1);
                }
                            
                            //System.out.print(rowCount);
                            if(model.getRowCount() == 0)
                            {
                                JOptionPane.showMessageDialog(null,"Vehicle registration number not found.","Error",JOptionPane.WARNING_MESSAGE);
                            resetFunction();
                            srchField.grabFocus();
                            
                            }
     
                
            
                
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
         jTable1.setAutoCreateRowSorter(true);
                              
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel notifLabel;
    private javax.swing.JTextField srchField;
    // End of variables declaration//GEN-END:variables
}
